# Generated by Django 5.1.4 on 2025-01-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_username', models.CharField(default='SS&CO.', max_length=100)),
                ('member_Memberid', models.CharField(max_length=100)),
                ('member_email', models.EmailField(max_length=100)),
                ('member_address', models.CharField(max_length=100)),
                ('member_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='members_invited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_id', models.CharField(max_length=100)),
                ('inviter_username', models.CharField(default='SS&CO.', max_length=100)),
                ('CODE', models.IntegerField()),
                ('member_username', models.CharField(max_length=100)),
                ('member_email', models.EmailField(max_length=100)),
                ('member_phone', models.CharField(max_length=100)),
                ('member_address', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=100)),
                ('invited_member_address', models.CharField(max_length=300)),
            ],
        ),
    ]
