# Generated by Django 5.1.4 on 2025-01-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSMAIN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_invited',
            name='invited_member_address',
        ),
        migrations.RemoveField(
            model_name='members_invited',
            name='member_id',
        ),
    ]
