# Generated by Django 5.1.4 on 2025-01-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSMAIN', '0002_remove_members_invited_invited_member_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members_invited',
            old_name='member_address',
            new_name='inviter_memberid',
        ),
        migrations.RemoveField(
            model_name='members_invited',
            name='inviter_username',
        ),
        migrations.RemoveField(
            model_name='members_invited',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='members_invited',
            name='member_phone',
        ),
        migrations.RemoveField(
            model_name='members_invited',
            name='member_username',
        ),
    ]
