# Generated by Django 5.1.4 on 2025-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSMAIN', '0003_rename_member_address_members_invited_inviter_memberid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_invited',
            name='INVITED_ADDRESS',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members_invited',
            name='INVITED_EMAIL',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
