# Generated by Django 5.1.4 on 2025-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSSS', '0002_ssss_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssss_products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
