# Generated by Django 5.1.4 on 2025-01-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSSS', '0003_alter_ssss_products_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSSS_artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField()),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_image', models.ImageField(upload_to='images')),
                ('artist_description', models.CharField(max_length=500)),
            ],
        ),
    ]
