# Generated by Django 5.1.4 on 2025-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PearlM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_pmclub',
            name='product_monarch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
