# Generated by Django 5.1.4 on 2025-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PearlM', '0002_alter_product_pmclub_product_monarch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_pmclub',
            name='product_monarch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
