# Generated by Django 5.1.4 on 2025-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PearlM', '0003_alter_product_pmclub_product_monarch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_pmclub',
            name='product_image',
            field=models.ImageField(upload_to='PearlM/static'),
        ),
    ]
