# Generated by Django 5.1.4 on 2025-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PearlM', '0005_alter_product_pmclub_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_pmclub',
            name='product_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
