# Generated by Django 5.1.4 on 2025-02-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PearlM', '0009_alter_product_pmclub_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_pmclub',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
