# Generated by Django 5.1.4 on 2025-01-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCClub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccmembers',
            old_name='name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='ccmembers',
            name='SSkey',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccmembers',
            name='username',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
