# Generated by Django 5.1.4 on 2025-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CCClub', '0003_delete_ccmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_CCClub',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_name', models.CharField(max_length=30)),
                ('art_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('art_description', models.CharField(max_length=30)),
                ('art_title', models.CharField(max_length=30)),
                ('art_img', models.ImageField(upload_to='CCClub/static')),
            ],
        ),
    ]
