# Generated by Django 5.1.4 on 2025-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCClub', '0005_alter_product_ccclub_art_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ccclub',
            name='art_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
